version: "3"
# Start from cmd line: docker-compose up -d
# Or directly from IntelliJ IDEA
# Inspiration for more containers:
# https://github.com/akka/alpakka/blob/8b1b3046d45dddeac2a5d12801d7c34476786a41/docker-compose.yml

services:
  # https://github.com/vromero/activemq-artemis-docker
  artemis:
    restart: always
    image: vromero/activemq-artemis:2.9.0-alpine
    hostname: artemis
    networks:
      - runtime-net
    ports:
      - "8161:8161"
      - "21616:61616"
      - "21613:61613"
      - "1199:1199"
      - "1198:1198"
    environment:
      - ENABLE_JMX=true
      - JMX_PORT=1199
      - JMX_RMI_PORT=1198

  atmoz_sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"
    command: echouser:password:::echo

  # https://github.com/stilliard/docker-pure-ftpd
  pure_ftpd:
    image: stilliard/pure-ftpd:latest
    ports:
      - "21000:21"
      - "30000-30009:30000-30009"
    environment:
      - PUBLICHOST=172.22.0.1
      - FTP_USER_NAME=echouser
      - FTP_USER_PASS=password
      - FTP_USER_HOME=/home/echouser
      - FTP_USER_UID=2000
      - FTP_USER_GID=2000

networks:
  runtime-net: